import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppBar, Toolbar,Typography, Container,
  IconButton,Box,InputBase,Drawer,List,ListItem,ListItemText,Button } from "@mui/material";
  import PrintIcon from "@mui/icons-material/Print";
  import SearchIcon from "@mui/icons-material/Search";
  import HelpOutlineIcon from "@mui/icons-material/HelpOutline";
  import LogoutIcon from "@mui/icons-material/Logout";
import ThemeRegistry from "./ThemeRegistry";
import Image from "next/image"
import Link from "next/link";
import Footer from "@/components/Footer";
import { AccountProvider } from "@/context/AccountContext";
import ClientNavbar from "@/components/ClientNavbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{
  children: React.ReactNode;}>) {
    
  return (
    <html lang="en">
         <body>
        <ThemeRegistry>
          <AccountProvider>
            <ClientNavbar />
            <main>{children}</main>
            <Footer />
          </AccountProvider>
        </ThemeRegistry>
      </body>

    </html>
  );
}
